# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-11-23 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seurat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='try',
            name='minCells',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='try',
            name='minGenes',
            field=models.IntegerField(null=True),
        ),
    ]
